version: '3.9'

networks:
  web_network:
    name: laravel5.2
    driver: bridge

services:

  # PHP App Service 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel5.2-app
    restart: always
    volumes:
      - ./src:/var/www
    networks:
      - web_network 

  # Nginx Web Server Service
  nginx:
    image: nginx:1.19.8-alpine
    container_name: laravel5.2_nginx
    volumes:
      - ./src:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "8100:80"
    restart: always
    networks:
      - web_network